#!/usr/bin/env bash

# This script wraps the calls to docker compose run to fire up CLI commands within the backend container

set -euo pipefail
readonly scriptDir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
echo $scriptDir
cd $scriptDir

readonly arg=${1:-"'not set'"}
echo "matching command '$arg'"

readonly composeRunBackend="docker-compose run -w /usr/src/app backend "

case "$arg"} in
    i*)
        echo "Install"
        $composeRunBackend yarn install
        ;;
    u*)
        echo "Update"
        $composeRunBackend yarn
        ;;
    m*)
        echo "run DB migrations"
        $composeRunBackend npx prisma migrate dev
        ;;
    g*)
        echo "generate client"
        $composeRunBackend npx prisma generate
        ;;
    *)
        echo "invalid command"
        printf "\n\nInvalid command $arg\n\n" && exit 1
        ;;
esac