#!/usr/bin/env bash

# This script wraps the calls to docker compose run to fire up CLI commands within the backend container

#BASH safe error handling
set -euo pipefail

# Entering project root directory
readonly scriptDir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
readonly projectRootDir=$(realpath $scriptDir/../)
cd $projectRootDir

# Getting argument
readonly arg=${1:-"'not set'"}

function composeRunBackend(){
    local runCmd="docker-compose run --rm backend "
    set -x
    $runCmd ${@}
}

case "$arg"} in
    i*)
        echo "Install"
        composeRunBackend yarn install
        ;;
    u*)
        echo "Update"
        composeRunBackend yarn
        ;;
    m*)
        echo "Run DB migrations"
        composeRunBackend npx prisma migrate dev
        ;;
    g*)
        echo "Generate client"
        composeRunBackend npx prisma generate
        ;;
    s*)
        echo "Running Prisma Studio"
        composeRunBackend npx prisma studio --browser none
        ;;
    *)
        echo "Invalid Command"
        printf "\n\nInvalid command $arg\n\n" && exit 1
        ;;
esac